
[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "ShureTechMono Nerd Font"
#family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "UbuntuMono Nerd Font"
family = "ShureTechMono Nerd Font"
style = "Bold Italic"

[font.italic]
#family = "UbuntuMono Nerd Font"
family = "ShureTechMono Nerd Font"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font"
#family = "UbuntuMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.6
blur = true

option_as_alt = "Both"

[cursor]
style.shape = "Beam"
style.blinking = "On"
